# 单独的输入模版
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: standalone-print
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["standalone-print-{{inputs.parameters.message}}"]